AppBundle\Entity\Portada:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: ['list']
        imageName:
            expose: true
            groups: ['list']

