AppBundle\Entity\Mensaje:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: ['list']
        informacion:
            expose: true
            groups: ['list']
        fechaHora:
            expose: true
            groups: ['list']
        user:
            expose: true
            groups: ['list']
        imageName:
            expose: true
            groups: ['list']
        meGustas:
            expose: true
            groups: ['list']
        longitud:
            expose: true
            groups: ['list']
        latitud:
            expose: true
            groups: ['list']
